/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_autel_sqlitememory_MainActivity */

#ifndef _Included_com_autel_sqlitememory_MainActivity
#define _Included_com_autel_sqlitememory_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_autel_sqlitememory_MainActivity
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_autel_sqlitememory_MainActivity_test
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
